<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf04b639627ed7b475f6bcca5b8f99bed
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'Madcoda\\Youtube\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Madcoda\\Youtube\\' => 
        array (
            0 => __DIR__ . '/..' . '/madcoda/php-youtube-api/src',
        ),
    );

    public static $classMap = array (
        'Madcoda\\compat' => __DIR__ . '/..' . '/madcoda/php-youtube-api/src/compat.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf04b639627ed7b475f6bcca5b8f99bed::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf04b639627ed7b475f6bcca5b8f99bed::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitf04b639627ed7b475f6bcca5b8f99bed::$classMap;

        }, null, ClassLoader::class);
    }
}
